# Generated by Django 4.2 on 2026-05-01 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('berita', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='berita',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('published', 'Published'), ('archived', 'Archived')], default='pending', max_length=10),
        ),
    ]
