# Generated by Django 4.2 on 2026-05-01 13:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('berita', '0002_alter_berita_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Komentar',
            fields=[
                ('id_komentar', models.AutoField(primary_key=True, serialize=False)),
                ('isi_komentar', models.TextField()),
                ('tgl_komentar', models.DateTimeField(auto_now_add=True)),
                ('berita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='komentar', to='berita.berita')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
