# Generated by Django 4.2 on 2026-05-01 14:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('berita', '0003_komentar'),
    ]

    operations = [
        migrations.AddField(
            model_name='berita',
            name='share_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='bookmark',
            unique_together={('user', 'berita')},
        ),
        migrations.CreateModel(
            name='Notifikasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipe', models.CharField(choices=[('berita', 'Berita Baru'), ('komentar', 'Komentar Baru')], max_length=10)),
                ('judul', models.CharField(max_length=255)),
                ('pesan', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('tgl_notifikasi', models.DateTimeField(auto_now_add=True)),
                ('link_id', models.IntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifikasi', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-tgl_notifikasi'],
            },
        ),
        migrations.CreateModel(
            name='Reaksi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipe_reaksi', models.CharField(choices=[('wow', 'Wow'), ('idea', 'Idea'), ('thinking', 'Thinking'), ('sad', 'Sad'), ('down', 'Down'), ('love', 'Love')], max_length=10)),
                ('berita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reaksi_list', to='berita.berita')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('berita', 'user')},
            },
        ),
    ]
