# Generated by Django 4.2 on 2026-05-01 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('berita', '0004_berita_share_count_bookmark_is_archived_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='berita',
            name='feedback_admin',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='berita',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('published', 'Published'), ('rejected', 'Rejected'), ('archived', 'Archived')], default='draft', max_length=10),
        ),
    ]
