# Generated by Django 4.2 on 2026-05-01 16:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('berita', '0005_berita_feedback_admin_alter_berita_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kategori',
            options={'ordering': ['urutan_tampil', 'nama_kategori']},
        ),
        migrations.AddField(
            model_name='kategori',
            name='deskripsi',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kategori',
            name='icon',
            field=models.CharField(default='bi-tag', max_length=50),
        ),
        migrations.AddField(
            model_name='kategori',
            name='tgl_diperbarui',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='kategori',
            name='urutan_tampil',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='kategori',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.CreateModel(
            name='LogAktivitas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aksi', models.CharField(max_length=255)),
                ('icon_type', models.CharField(default='edit', max_length=20)),
                ('waktu', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-waktu'],
            },
        ),
    ]
